apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: pagina-web
    environment: testing
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80